apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  labels:
    app: kube-registry
spec:
  type: NodePort
  ports:
    - name: registry
      port: 5000
      protocol: TCP 
      nodePort: 30120
    - name: registry-ui
      port: 80
      protocol: TCP
      nodePort: 30220 
  selector:
    app: kube-registry
